export const LOGO_SCREEN = 'LOGO_SCREEN';
export const LOG_IN_SCREEN = 'LOG_IN_SCREEN';
export const START_UP_SCREEN = 'START_UP_SCREEN';
export const LOG_OUT_SCREEN = 'LOG_OUT_SCREEN';
export const EMPLOYEE_LIST_SCREEN = 'EMPLOYEE_LIST_SCREEN';
export const ADD_EMPLOYEE_SCREEN = 'ADD_EMPLOYEE_SCREEN';